"""init schema

Revision ID: f794f9e8b139
Revises: 
Create Date: 2025-12-19 06:27:33.456023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f794f9e8b139'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plagiarism_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('internal_doc_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plagiarism_percentage', sa.Float(), nullable=False),
    sa.Column('selfcite_percentage', sa.Float(), nullable=False),
    sa.Column('legal_percentage', sa.Float(), nullable=False),
    sa.Column('unknown_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_id', name='uq_plagiarism_reports_org_doc')
    )
    op.create_index('idx_plagiarism_reports_org_processed', 'plagiarism_reports', ['organization_id', 'processed_at'], unique=False)
    op.create_index('idx_plagiarism_reports_org_shard_processed', 'plagiarism_reports', ['organization_id', 'shard_id', 'processed_at'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('shingle_count', sa.BigInteger(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_compacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segments_org_shard_level_status', 'segments', ['organization_id', 'shard_id', 'level', 'status'], unique=False)
    op.create_index('idx_segments_org_shard_status_level', 'segments', ['organization_id', 'shard_id', 'status', 'level'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('simhash_hi', sa.BigInteger(), nullable=True),
    sa.Column('simhash_lo', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('student_name', sa.Text(), nullable=True),
    sa.Column('university', sa.Text(), nullable=True),
    sa.Column('faculty', sa.Text(), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_org_shard_status_seg', 'documents', ['organization_id', 'shard_id', 'status', 'segment_id'], unique=False)
    op.create_index('idx_documents_segment_id', 'documents', ['segment_id'], unique=False)
    op.create_table('plagiarism_report_matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('q_offset', sa.Integer(), nullable=False),
    sa.Column('q_limit', sa.Integer(), nullable=False),
    sa.Column('s_offset', sa.Integer(), nullable=False),
    sa.Column('s_limit', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('q_from', sa.Integer(), nullable=True),
    sa.Column('q_to', sa.Integer(), nullable=True),
    sa.Column('d_from', sa.Integer(), nullable=True),
    sa.Column('d_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['plagiarism_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prm_report_source', 'plagiarism_report_matches', ['report_id', 'source_id'], unique=False)
    op.create_table('plagiarism_report_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('internal_source_doc_id', sa.BigInteger(), nullable=True),
    sa.Column('module_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('index_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['plagiarism_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'source_id', name='uq_pr_sources_report_source')
    )
    op.create_index('idx_pr_sources_internal_source_doc_id', 'plagiarism_report_sources', ['internal_source_doc_id'], unique=False)
    op.create_index('idx_pr_sources_report', 'plagiarism_report_sources', ['report_id'], unique=False)
    op.create_table('index_errors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.BigInteger(), nullable=True),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_index_errors_created_at', 'index_errors', ['created_at'], unique=False)
    op.create_index('idx_index_errors_doc_id', 'index_errors', ['doc_id'], unique=False)
    op.create_index('idx_index_errors_segment_id', 'index_errors', ['segment_id'], unique=False)
    op.create_index('idx_index_errors_stage_created', 'index_errors', ['stage', 'created_at'], unique=False)
    op.create_table('segment_docs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'document_id', name='uq_segment_docs_segment_document')
    )
    op.create_index('idx_segment_docs_doc', 'segment_docs', ['document_id'], unique=False)
    op.create_index('idx_segment_docs_org_segment', 'segment_docs', ['organization_id', 'segment_id'], unique=False)
    op.create_index('idx_segment_docs_org_shard', 'segment_docs', ['organization_id', 'shard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_segment_docs_org_shard', table_name='segment_docs')
    op.drop_index('idx_segment_docs_org_segment', table_name='segment_docs')
    op.drop_index('idx_segment_docs_doc', table_name='segment_docs')
    op.drop_table('segment_docs')
    op.drop_index('idx_index_errors_stage_created', table_name='index_errors')
    op.drop_index('idx_index_errors_segment_id', table_name='index_errors')
    op.drop_index('idx_index_errors_doc_id', table_name='index_errors')
    op.drop_index('idx_index_errors_created_at', table_name='index_errors')
    op.drop_table('index_errors')
    op.drop_index('idx_pr_sources_report', table_name='plagiarism_report_sources')
    op.drop_index('idx_pr_sources_internal_source_doc_id', table_name='plagiarism_report_sources')
    op.drop_table('plagiarism_report_sources')
    op.drop_index('idx_prm_report_source', table_name='plagiarism_report_matches')
    op.drop_table('plagiarism_report_matches')
    op.drop_index('idx_documents_segment_id', table_name='documents')
    op.drop_index('idx_documents_org_shard_status_seg', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_segments_org_shard_status_level', table_name='segments')
    op.drop_index('idx_segments_org_shard_level_status', table_name='segments')
    op.drop_table('segments')
    op.drop_index('idx_plagiarism_reports_org_shard_processed', table_name='plagiarism_reports')
    op.drop_index('idx_plagiarism_reports_org_processed', table_name='plagiarism_reports')
    op.drop_table('plagiarism_reports')
    # ### end Alembic commands ###
